config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root "messages#new"
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages.json
  def index
    respond_to do |format|
      format.json { render json: {messages: Message.all.order(created_at: :asc).as_json} }
      
    end
  end

  # GET /messages/new
  def new
    @messages = Message.all.order(created_at: :asc)
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.create(message_params)
    ActionCable.server.broadcast("chatting_channel", {
      data_type: "message",
      user_id: @message.user_id, 
      content: @message.content,
      created_at: (@message.created_at.strftime("%m/%d %H:%M")),
    }) if @message.present?
    head :ok

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/css/line-awesome.min.css" integrity="sha512-vebUliqxrVkBy3gucMhClmyQP9On/HAWQdKDXRaAlb/FKuTbxkjPKUyqVOxAcGwFDka79eTF+YXwfke1h3/wfg==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    
  </head>

  <body>
    <script>

      if (window.localStorage.getItem("USER_ID")) {
      } else {
        const USER_ID = Math.random().toString(36).substr(2, 9);
        window.localStorage.setItem("USER_ID", USER_ID);
      }
    </script>
    <%= yield %>
    
  </body>
</html>

app/views/messages/_form.html.erb
<div class="container my-3">

  <div class="messages-content">
    <div class="card border-radius mb-0">
      <div class="card-body p-5">
        <div class="vertical-align">
          <div class="no-border">
            <div id="chat" class="conv-form-wrapper">
              <div class="wrapper-messages">
                <div class="messages pt-5" id="messages" style="position:unset">
                  
                </div>
              </div>
              <%= form_for Message.new, html: {class: "mt-5"},remote: true do |f| %>
                <%= f.hidden_field :user_id %>
                <%= f.text_area :content, class: "form-control", placeholder: "여기에 메시지를 입력하세요" %>
                <div class="text-right mt-2">
                  <%= f.submit "입력", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

<script>
const currentUserId = window.localStorage.getItem("USER_ID")

$(function(){
  $.getJSON('/messages', function(data) {
    data["messages"].forEach((message, i) => {
      let date = new Date(message.created_at)
      let msgSender =  (message.user_id == currentUserId ? 'from' : 'to')
      $("#messages").append(`
        <div class="message-box ${msgSender}">
          <div class="message ${msgSender}">
            ${message.content}
          </div>
          <div class="message ${msgSender}" style="background: white; color: dimgray; padding: 0px; font-size: 8px; vertical-align: bottom;">
            ${date.getMonth()}/${date.getDate()} ${date.getHours()}:${String(date.getMinutes()).padStart(2, "0")}
          </div>
        </div>
      `)

    })
    

  });

  $("#new_message").find("#message_user_id").val(currentUserId);

  $("#messages").scrollTop($("#messages")[0].scrollHeight)
  $('#message_content').on('keydown', function(e){
    if(e.keyCode == 13 && !e.shiftKey){
      // enter key 입력 시 줄바꿈
      $('input').click();
      e.target.value = ''
      e.preventDefault();
    }
  })

})
</script>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>